# Generated by Django 3.0.4 on 2020-03-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名字')),
                ('num', models.CharField(max_length=10, verbose_name='商品库存')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品描述')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shopapp.Category', verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Taokushop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='商品名字')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taokushops', to='shopapp.Good', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='商品名字')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='shopapp.Good', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Internation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='商品名字')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internations', to='shopapp.Good', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='GoodImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goodimg', verbose_name='商品展示图')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='shopapp.Good', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='商品名字')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashs', to='shopapp.Good', verbose_name='商品')),
            ],
        ),
    ]
